id: IEABED393
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T19:40:30+00:00'
last_modified: '2022-06-08T00:51:35.056386+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1869
  title: རི་ཆོས་ངེས་དོན་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3E38:
      image_group_id: I1KG1873
      title: ''
      total_pages: 458
      order: 1
      base_file: 3E38.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
